# Generated by Django 5.2.5 on 2025-09-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
